### ISSUE TITLE
solved

### ISSUE THREAD

**Issue by michaelcodecany** [ArpitShukIa/IpfsImageUploader#1]

**Comment by ArpitShukIa** [comment]
Hi @michaelcodecany,
> HTTPError: basic auth failure: invalid project id or project secret

Have you created an **IPFS** project at Infura? (https://infura.io/product/ipfs

**Comment by michaelcodecany** [comment]
Yes I did.

**Comment by ArpitShukIa** [comment]
I had also faced this error once and was able to fix it just by using the right keys.
After creating an IPFS project at Infura, you get the Project Id and Api Ket Secret which you can put in your `.env`.
You would also need to create a unique subdomain for the project.

Following is the UI from where you get the keys:

![Screenshot 2022-08-21 at 7 18 43 PM](https://user-images.githubusercontent.com/51705072/185794284-b5f0c5f4-047d-4fab-8b32-8bcf57b82833.png)
